### ISSUE TITLE
方块排列有问题

### ISSUE THREAD

**Issue by desperadoray** [AJLoveChina/CleanBombs#1]
在chrome上显示的不是NxN的排列

**Comment by AJLoveChina** [comment]
@desperadoray  是酱紫的, 我当时没把它设计成NxN是为了在手机端可以很好的显示, 比如王者级别的难度有1000个方块,如果设计成NxN 手机上操作不方便(需要左右滑动).  当时这个程序是给一个微信公众号设计的,它的用户群基本上都是手机端使用.

**Comment by desperadoray** [comment]
哈哈谢谢告知
